[project]
name = "simpler-server-setup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp-proxy>=0.8.0",
    "mcp[cli]>=1.10.1",
]
